using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;
using QuantumIT.Sample.Microservices.Interface.ORM;

namespace QuantumIT.Sample.Microservices.ORM
{
    public class DBProvider : IDBProvider
    {
        protected bool disposedValue = false;
        protected IDbTransaction _openTransaction;
        protected IDbConnection _dbconnection;
        protected readonly IDapperWrapper _dapper;
        protected readonly IDBHelper _dbHelper;

        public DBProvider(IDbConnection dbconnection, IDapperWrapper dapper, IDBHelper dbHelper)
        {
            _dbconnection = dbconnection;
            _dapper = dapper;
            _dbHelper = dbHelper;
        }

        public virtual Task<int> AddAsync<T>(T entity)
        {
            return AddAsync<T>(entity, null);
        }

        public virtual async Task<int> AddAsync<T>(T entity, string[] ignoreParameters)
        {
            var query = $"INSERT INTO {typeof(T).Name} ({_dbHelper.ConstructColumsForInsert<T>(ignoreParameters)}) VALUES ({_dbHelper.ConstructParamsForInsert<T>(ignoreParameters)});SELECT LAST_INSERT_ID();";
            var result = await _dapper.QueryAsync<int>(_dbconnection, query, entity, _openTransaction);

            return result.Single();
        }

        public virtual Task<int> AddRangeAsync<T>(IEnumerable<T> entity)
        {
            return AddRangeAsync<T>(entity, null);
        }

        public virtual async Task<int> AddRangeAsync<T>(IEnumerable<T> entities, string[] ignoreParameters = null)
        {
            var query = $"INSERT INTO {typeof(T).Name} ({_dbHelper.ConstructColumsForInsert<T>(ignoreParameters)}) VALUES ({_dbHelper.ConstructParamsForInsert<T>(ignoreParameters)});";
            return await _dapper.ExecuteAsync(_dbconnection, query, entities, _openTransaction);
        }

        public virtual async Task<int> AddRangeWithQueryAsync<T>(string query, IEnumerable<T> entities, string[] ignoreParameters = null)
        {
            return await _dapper.ExecuteAsync(_dbconnection, query, entities, _openTransaction);
        }

        public async Task<IEnumerable<T>> GetAsync<T>(bool enabled = true)
        {
            return await GetAsync<T>($"select * from {typeof(T).Name} where Enabled=@Enabled", new { Enabled = enabled });
        }

        public async Task<T> GetByIdAsync<T>(string id, string keyName, bool enabled = true)
        {
            var result = await GetAsync<T>($"select * from {typeof(T).Name} WHERE {keyName}=@Id and Enabled=@Enabled", new { Id = id, Enabled = enabled });
            return result.SingleOrDefault();
        }

        public async Task<IEnumerable<T>> GetAsync<T>(string query, object param = null)
        {
            return await _dapper.QueryAsync<T>(_dbconnection, query, param);
        }

        public void CloseConnection()
        {
            if (_dbconnection.State != ConnectionState.Closed)
            {
                _dbconnection.Close();
            }
        }

        public async Task OpenConnectionAsync()
        {
            if (null == _dbconnection || _dbconnection.State == ConnectionState.Closed)
            {
                await ((DbConnection)_dbconnection).OpenAsync().ConfigureAwait(false);
            }
        }
        public async Task<IDbTransaction> InitTransactionAsync(IsolationLevel isolationLevel)
        {
            if (null == _openTransaction)
            {
                await OpenConnectionAsync();
                _openTransaction = await ((MySqlConnection)_dbconnection).BeginTransactionAsync(isolationLevel);
            }
            return _openTransaction;
        }

        public void CommitTransaction()
        {
            if (null != _openTransaction)
            {
                _openTransaction.Commit();
                _openTransaction.Dispose();
                _openTransaction = null;
            }
        }

        //https://stackoverflow.com/questions/31152954/is-it-possible-to-commit-rollback-sqltransaction-in-asynchronous

        public void RollbackTransaction()
        {
            if (null != _openTransaction)
            {
                _openTransaction.Rollback();
                _openTransaction.Dispose();
                _openTransaction = null;
            }
        }

        public virtual async Task<int> DeleteAsync<T>(int entityId, string[] ignoreParameters = null)
        {
            var query = $"UPDATE {typeof(T).Name} SET Enabled=false,ModifiedOn=@ModifiedOn Where {_dbHelper.GetPrimaryKeyAutoGenerated<T>()} = @Id and Enabled=true;";
            var count = await _dapper.ExecuteAsync(_dbconnection, query, new { Id = entityId, ModifiedOn = DateTime.UtcNow }, _openTransaction);
            return count;
        }


        public virtual async Task<int> UpdateAsync<T>(T entity, string[] ignoreParameters = null)
        {
            var query = $"UPDATE {typeof(T).Name} SET {_dbHelper.ConstructColumsForUpdate<T>(ignoreParameters)} Where {_dbHelper.GetPrimaryKeyAutoGenerated<T>()}=@{_dbHelper.GetPrimaryKeyAutoGenerated<T>()} and Enabled=True;";
            var count = await _dapper.ExecuteAsync(_dbconnection, query, entity, _openTransaction);
            return count;
        }

        public virtual async Task<int> UpdateWithoutCOALSCEAsync<T>(T entity, string[] ignoreParameters = null)
        {
            var query = $"UPDATE {typeof(T).Name} SET {_dbHelper.ConstructColumsForUpdateWithoutCOALESCE<T>(ignoreParameters)} Where {_dbHelper.GetPrimaryKeyAutoGenerated<T>()}=@{_dbHelper.GetPrimaryKeyAutoGenerated<T>()} and Enabled=True;";
            var count = await _dapper.ExecuteAsync(_dbconnection, query, entity, _openTransaction);
            return count;
        }

        public virtual async Task<int> UpdateRangeAsync<T>(IEnumerable<T> entities, string[] ByIds, string[] ignoreParameters = null)
        {
            var query = $"UPDATE {typeof(T).Name} SET {_dbHelper.ConstructColumsForUpdate<T>(ignoreParameters)} Where {_dbHelper.ConstructColumsForUpdateWithKeys<T>(ByIds)} and Enabled=True;";
            var count = await _dapper.ExecuteAsync(_dbconnection, query, entities, _openTransaction);
            return count;
        }

        public virtual async Task<IDictionary<Type, IEnumerable<object>>> QueryMultiple(string query, object parameters, IEnumerable<Type> returnTypes)
        {
            var results = new Dictionary<Type, IEnumerable<object>>();
            using (var multiResult = await _dapper.QueryMultipleAsync(_dbconnection, query, parameters, _openTransaction))
            {
                if (multiResult == null)
                    return results;

                foreach (Type returnType in returnTypes)
                {
                    var returnValues = await multiResult.ReadAsync(returnType).ConfigureAwait(false);
                    if (returnValues.Any())
                        results.Add(returnType, returnValues);
                    else
                        results.Add(returnType, null);
                }
            }
            return results;
        }


        public async Task<IEnumerable<T>> GetByQuery<Q, S, T>(string query, Func<Q, S, T> map, object param = null, string splitOn = "Id")
        {
            return await _dapper.Query<Q, S, T>(_dbconnection, map, query, param, _openTransaction, true, null, null, splitOn).ConfigureAwait(false);
        }

        public async Task<IEnumerable<T>> GetByQuery<Q, R, S, T>(string query, Func<Q, R, S, T> map, object param = null, string splitOn = "Id")
        {
            return await _dapper.Query<Q, R, S, T>(_dbconnection, map, query, param, _openTransaction, true, null, null, splitOn).ConfigureAwait(false);
        }


        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    if (_openTransaction != null)
                    {
                        _openTransaction.Rollback();
                        _openTransaction.Dispose();
                    }
                    if (_dbconnection.State != ConnectionState.Closed)
                    {
                        _dbconnection.Close();
                    }

                    _dbconnection.Dispose();
                    _dbconnection = null;
                    _openTransaction = null;
                }

                disposedValue = true;
            }
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }


    }
}
